### ISSUE TITLE
unable to install using npm

### ISSUE THREAD

**Issue by panama69** [MicroFocus/alm-octane-js-rest-sdk#24]
Based on the instructions, I should be able to perform the following command from with in the cloned project
```
npm i @microfocus/alm-octane-js-rest-sdk
```
However, upon executing the command, I receive the following:
````
/Users/flynn/node-projects/alm-octane-js-rest-sdk
Davids-MacBook-Pro-4:alm-octane-js-rest-sdk flynn$ ls -al
total 208
drwxr-xr-x  14 flynn  staff    448 Oct  9 21:37 .
drwxr-xr-x   7 flynn  staff    224 Oct  9 21:37 ..
drwxr-xr-x  13 flynn  staff    416 Oct  9 21:37 .git
-rw-r--r--   1 flynn  staff   1670 Oct  9 21:37 .gitignore
drwxr-xr-x  10 flynn  staff    320 Oct  9 21:37 .idea
-rw-r--r--   1 flynn  staff    577 Oct  9 21:37 LICENSE
-rw-r--r--   1 flynn  staff   9420 Oct  9 21:37 README.md
-rw-r--r--   1 flynn  staff    457 Oct  9 21:37 alm_octane_js_rest_sdk.iml
drwxr-xr-x   7 flynn  staff    224 Oct  9 21:37 lib
-rw-r--r--   1 flynn  staff  76570 Oct  9 21:37 package-lock.json
-rw-r--r--   1 flynn  staff   1432 Oct  9 21:37 package.json
drwxr-xr-x   3 flynn  staff     96 Oct  9 21:37 routes
drwxr-xr-x   4 flynn  staff    128 Oct  9 21:37 scripts
drwxr-xr-x   8 flynn  staff    256 Oct  9 21:37 test
Davids-MacBook-Pro-4:alm-octane-js-rest-sdk flynn$ npm i @microfocus/alm-octane-js-rest-sdk
npm ERR! code E404
npm ERR! 404 Not Found: @microfocus/alm-octane-js-rest-sdk@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/flynn/.npm/_logs/2018-10-10T02_41_09_499Z-debug.log
Davids-MacBook-Pro-4:alm-octane-js-rest-sdk flynn$ npm i @microfocus/alm-octane-js-rest-sdk
````
The following is what is found in the /Users/flynn/.npm/_logs/2018-10-10T02_41_09_499Z-debug.log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@microfocus/alm-octane-js-rest-sdk' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session 7b09286c0be10709
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@microfocus%2falm-octane-js-rest-sdk 668ms
8 silly fetchPackageMetaData error for @microfocus/alm-octane-js-rest-sdk@latest 404 Not Found: @microfocus/alm-octane-js-rest-sdk@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 950ms
11 verbose stack Error: 404 Not Found: @microfocus/alm-octane-js-rest-sdk@latest
11 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:693:18)
11 verbose stack     at tryOnImmediate (timers.js:664:5)
11 verbose stack     at processImmediate (timers.js:646:5)
12 verbose cwd /Users/flynn/node-projects/alm-octane-js-rest-sdk
13 verbose Darwin 17.7.0
14 verbose argv "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/bin/npm" "i" "@microfocus/alm-octane-js-rest-sdk"
15 verbose node v10.9.0
16 verbose npm  v6.2.0
17 error code E404
18 error 404 Not Found: @microfocus/alm-octane-js-rest-sdk@latest
19 verbose exit [ 1, true ]
```

**Comment by slbruce** [comment]
This has been fixed.  The latest release had not been updated in NPM.  It is available there now
