### ISSUE TITLE
generate_api_annotations.js fails

### ISSUE THREAD

**Issue by swar30** [MicroFocus/alm-octane-js-rest-sdk#29]
after installing library on windows when running `generate_api_annotations.js` like so  
`c:\app>node node_modules\@microfocus\alm-octane-js-rest-sdk\scripts\generate_api_annotations.js c:\app\octane.json`  
failing with error
```
generating api annotations ...
loading default routes file ...
{ Error: ENOENT: no such file or directory, open 'c:\app\node_modules\@microfocus\alm-octane-js-rest-sdk\routes\default.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at generateAPIAnnotations (c:\app\node_modules\@microfocus\alm-octane-js-rest-sdk\scripts\generate_api_annotations.js:37:10)
    at Object.<anonymous> (c:\app\node_modules\@microfocus\alm-octane-js-rest-sdk\scripts\generate_api_annotations.js:176:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\app\\node_modules\\@microfocus\\alm-octane-js-rest-sdk\\routes\\default.json' }
```
Any chance missing check if file exists or forgot to add file to npm package ?

If adding empty JSON file, it will run but than fail again, this time on missing doc file.

**Comment by slbruce** [comment]
Please use the `generate_default_routes.js` script.
